name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日0時に実行
  workflow_dispatch:

permissions:
  contents: write  # mainブランチにpushするので必要

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Marstach-svg
          outputs: |
            img/github-user-contribution.svg

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add img/github-user-contribution.svg
          git commit -m "update snake contribution graph" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
